### ISSUE TITLE
trained model availability?

### ISSUE THREAD

**Issue by qwang-big** [aetherAI/whole-slide-cnn#1]
Dear authors,

I am led here following your paper in nature communications. I wonder is the model file available for a test on some in-house whole slide images? Thanks!

Best regards,
QW

**Comment by luciantunez** [comment]
same here! thanks :)

**Comment by chenchc** [comment]
Hi QW and luciantunez,

Sorry for the late response. Somehow Github didn't notify me of this...

We cannot release the model file trained on our in-house lung data set due to privacy issues. 
However, we can prepare a model trained on public datasets, TCGA-LUAD and TCGA-LUSC, for you to evaluate.
Please give me a few days to get this done.
Thanks.

Best,
Chi-Chung

**Comment by luantunez** [comment]
Thank you very much! You are really kind!

**Comment by chenchc** [comment]
Hi @qwang-big @luantunez and @luciantunez,

Glad to tell you that we have uploaded a pre-trained model trained by the TCGA-LUAD and TCGA-LUSC datasets.
Please see the info on the homepage and have a try.
Feel free to contact me if you encounter any problems.

Best,
Chi-Chung
